variable "ip_configuration_subnet_id" {}
variable "storage_image_reference_id" {}
variable "zone_name" {}
variable "network_security_group_id" {}
variable "databases" {}
variable "applications" {}
variable "rg_name" {}
variable "env" {}
variable "aks" {}
variable "token" {}